// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Rx00J85KS3HKz20PvSD8iCV2fRJwAmg',
    appId: '1:196834217391:web:309a312d123f653e03335a',
    messagingSenderId: '196834217391',
    projectId: 'rocos-rex-flutterstudy-001',
    authDomain: 'rocos-rex-flutterstudy-001.firebaseapp.com',
    storageBucket: 'rocos-rex-flutterstudy-001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-DNP-b28TXTbooaXL52eCqq1UhDBQ3Zk',
    appId: '1:196834217391:android:91ae59e3a34b463403335a',
    messagingSenderId: '196834217391',
    projectId: 'rocos-rex-flutterstudy-001',
    storageBucket: 'rocos-rex-flutterstudy-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6kQL98KXP0mV6J7oOvYCuNCiSDUV2cpw',
    appId: '1:196834217391:ios:d7e9179f1c77b5dd03335a',
    messagingSenderId: '196834217391',
    projectId: 'rocos-rex-flutterstudy-001',
    storageBucket: 'rocos-rex-flutterstudy-001.appspot.com',
    iosClientId: '196834217391-daau522r0i39mo94vq75ntrkm3nrh2e5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6kQL98KXP0mV6J7oOvYCuNCiSDUV2cpw',
    appId: '1:196834217391:ios:d7e9179f1c77b5dd03335a',
    messagingSenderId: '196834217391',
    projectId: 'rocos-rex-flutterstudy-001',
    storageBucket: 'rocos-rex-flutterstudy-001.appspot.com',
    iosClientId: '196834217391-daau522r0i39mo94vq75ntrkm3nrh2e5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
